name: Tests

"on":
  push:
    branches: [main, dev]
  pull_request:
    branches: [main, dev]
    types: [opened, synchronize, reopened]
  workflow_call:
    secrets:
      COMPOSER_TOKEN:
        required: false

permissions:
  contents: read

jobs:
  quality:
    name: Quality
    uses: Ayup-Creative/workflows/.github/workflows/tests.yml@v1
    with:
      php_versions: '["8.3","8.4","8.5"]'
      phpstan_php_version: '8.4'
      composer_repositories: >-
        {"vendor-package":"https://github.com/example/vendor-package.git"}
    secrets:
      composer_token: ${{ secrets.COMPOSER_TOKEN }}
