# .github/workflows/weekly-release.yml

name: Nightly Release Promotion

"on":
  schedule:
    - cron: '17 3 * * *'
  workflow_dispatch:

permissions:
  contents: read
  checks: read
  statuses: read

jobs:
  promotion:
    name: Promote green development code
    uses: Ayup-Creative/workflows/.github/workflows/weekly-release.yml@v1
    secrets: inherit
