# .github/workflows/release.yml

name: Weekly Release

on:
  schedule:
    # 0 3 * * 1 - Weekly
    # 0 3 * * * - Nightly
    - cron: '0 3 * * 1'

  workflow_dispatch:

jobs:
  release:
    uses: ayup-creative/workflows/.github/workflows/weekly-release.yml@v1

    with:
      development-branch: dev
      release-branch: main
      required-check: Release Gate
      release-type: php

    secrets:
      release-token: ${{ secrets.RELEASE_TOKEN }}
